spring.application.name=AgendaContatoProducer
server.port=8081

rabbitmq.host=${SPRING_RABBITMQ_HOST:localhost}
rabbitmq.port=${SPRING_RABBITMQ_PORT:5672}
rabbitmq.username=${SPRING_RABBITMQ_USERNAME:guest}
rabbitmq.password=${SPRING_RABBITMQ_PASSWORD:guest}

jwt.secret=${JWT_SECRET}
jwt.expiration=3600000
