spring.application.name=AgendaContatoConsumer
spring.main.web-application-type=none

# Banco de Dados alinhado com o Docker Environment (incluindo a URL isolada)
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/agenda_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:admin}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:admin123}
spring.datasource.driver-class-name=org.postgresql.Driver

# Conexao com o RabbitMQ alinhada com o Docker Environment
rabbitmq.host=${SPRING_RABBITMQ_HOST:localhost}
rabbitmq.port=${SPRING_RABBITMQ_PORT:5672}
rabbitmq.username=${SPRING_RABBITMQ_USERNAME:guest}
rabbitmq.password=${SPRING_RABBITMQ_PASSWORD:guest}

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

